project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Hansen Wiguna"
  date: "1/19/2023"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

